WifiCountryCode: "CH"
VideoAntiFlickerRate: 50
VideoQualityDefault: "low"
NotifyRegisteredAndStatusUpdate: false
NotifyOnMotionAlert: false
NotifyOnMotionTimeoutAlert: false
NotifyOnAudioAlert: false
NotifyOnButtonPressAlert: false
